version: 0.2

phases:
  install:
    commands:
      - echo "Install phase..."
  pre_build:
    commands:
      - echo "Pre-build phase ..."
      - find . -name newsread.service -type f
      - find . -name run.py -type f
      - find . -name application -type d
      - echo "Pre-build complete"
  build:
    commands:
      - echo "Build phase ..."
      - pip3 install -r requirements.txt
      - export FLASK_APP=run.py
      - flask routes > routes.txt
  post_build:
    commands:
      - echo "Build completed on $(date)" >> routes.txt
artifacts:
  files:
    - routes.txt